server.port=8001
spring.application.name=restaurant-management
spring.main.allow-circular-references=true

spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=GMT+8
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss

spring.mvc.static-path-pattern=/**

logging.level.com.restaurant=DEBUG
logging.level.root=INFO